In [4]:
import numpy as np

In [5]:
array_1d = np.arange(10, 50)
print(array_1d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
array_reshaped = array_1d[:15].reshape(3, 5)
print(array_reshaped)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [7]:
divisible_by_3 = array_1d[array_1d % 3 == 0]
print(divisible_by_3)

[12 15 18 21 24 27 30 33 36 39 42 45 48]


In [11]:
array_random1 = np.random.randint(1, 10, size=(3, 3))
array_random2 = np.random.randint(1, 10, size=(3, 3))

print(array_random1)
print(array_random2)

[[8 4 7]
 [9 8 3]
 [7 9 9]]
[[2 3 4]
 [9 5 2]
 [7 9 7]]


In [13]:
add_result = array_random1 + array_random2
sub_result = array_random1 - array_random2
mul_result = array_random1 * array_random2
div_result = array_random1 / array_random2

print(add_result)
print(sub_result)
print(mul_result)
print(div_result)

[[10  7 11]
 [18 13  5]
 [14 18 16]]
[[6 1 3]
 [0 3 1]
 [0 0 2]]
[[16 12 28]
 [81 40  6]
 [49 81 63]]
[[4.         1.33333333 1.75      ]
 [1.         1.6        1.5       ]
 [1.         1.         1.28571429]]
